version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 5173:80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_DEV_API_ROOT=http://localhost:8017
    env_file:
      - ./frontend/.env 
    networks:
      - network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 8017:8017
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - LOCAL_DEV_APP_HOST=${LOCAL_DEV_APP_HOST}
      - LOCAL_DEV_APP_PORT=${LOCAL_DEV_APP_PORT}
      - WEBSITE_DOMAIN_DEVELOPMENT=${WEBSITE_DOMAIN_DEVELOPMENT}
      - WEBSITE_DOMAIN_PRODUCTION=${WEBSITE_DOMAIN_PRODUCTION}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS}
      - ADMIN_EMAIL_NAME=${ADMIN_EMAIL_NAME}
      - ACCESS_TOKEN_SECRET_SIGNATURE =${ACCESS_TOKEN_SECRET_SIGNATURE}
      - REFRESH_TOKEN_SECRET_SIGNATURE =${REFRESH_TOKEN_SECRET_SIGNATURE}
      - ACCESS_TOKEN_LIFE=${ACCESS_TOKEN_LIFE}
      - REFRESH_TOKEN_LIFE=${REFRESH_TOKEN_LIFE}
    env_file:
      - ./backend/.env 
    networks:
      - network


networks:
  network:
