version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_DEV_API_ROOT: http://${LOCAL_DEV_APP_HOST}:${LOCAL_DEV_APP_PORT}
    networks:
      - app_network
    volumes:
      - ./frontend:/app
      - /app/node_modules  # For node_modules caching inside the container

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: always
    ports:
      - "8017:8017"
    volumes:
      - ./backend:/app
      - /app/node_modules  # For node_modules caching inside the container
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - LOCAL_DEV_APP_HOST=${LOCAL_DEV_APP_HOST}
      - LOCAL_DEV_APP_PORT=${LOCAL_DEV_APP_PORT}
      - WEBSITE_DOMAIN_DEVELOPMENT=${WEBSITE_DOMAIN_DEVELOPMENT}
      - WEBSITE_DOMAIN_PRODUCTION=${WEBSITE_DOMAIN_PRODUCTION}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS}
      - ADMIN_EMAIL_NAME=${ADMIN_EMAIL_NAME}
      - ACCESS_TOKEN_SECRET_SIGNATURE=${ACCESS_TOKEN_SECRET_SIGNATURE}
      - REFRESH_TOKEN_SECRET_SIGNATURE=${REFRESH_TOKEN_SECRET_SIGNATURE}
      - ACCESS_TOKEN_LIFE=${ACCESS_TOKEN_LIFE}
      - REFRESH_TOKEN_LIFE=${REFRESH_TOKEN_LIFE}
    networks:
      - app_network

# Network configuration for communication between services
networks:
  app_network:
    driver: bridge
