services:
  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    ports:
      - 80:80
    environment:
      NODE_ENV: development
      VITE_DEV_API_ROOT: http://${LOCAL_DEV_APP_HOST}:${LOCAL_DEV_APP_PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_container
    restart: always
    ports:
      - 8017:8017
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME}
      - LOCAL_DEV_APP_HOST=${LOCAL_DEV_APP_HOST}
      - LOCAL_DEV_APP_PORT=${LOCAL_DEV_APP_PORT}
      - WEBSITE_DOMAIN_DEVELOPMENT=${WEBSITE_DOMAIN_DEVELOPMENT}
      - WEBSITE_DOMAIN_PRODUCTION=${WEBSITE_DOMAIN_PRODUCTION}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS}
      - ADMIN_EMAIL_NAME=${ADMIN_EMAIL_NAME}
      - ACCESS_TOKEN_SECRET_SIGNATURE=${ACCESS_TOKEN_SECRET_SIGNATURE}
      - REFRESH_TOKEN_SECRET_SIGNATURE=${REFRESH_TOKEN_SECRET_SIGNATURE}
      - ACCESS_TOKEN_LIFE=${ACCESS_TOKEN_LIFE}
      - REFRESH_TOKEN_LIFE=${REFRESH_TOKEN_LIFE}