name: API Testing 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js and Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      # Set up environment variables
      - name: Set up environment variables
        run: |
          cd backend
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "BUILD_MODE=dev" >> .env

      - name: Run tests
        working-directory: backend
        run: |
          yarn install
          yarn test
