name: API Testing 

on:
  push:
    branches:
      - feat/api-testing
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install dependencies
        run: cd backend && yarn

      - name: Run API tests
        run: yarn test
