name: Continuous Integration for Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Set up environment variables
        run: |
          cd backend
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "BUILD_MODE=dev" >> .env
          echo "TEST_DATABASE_NAME= taskflow_test" >> .env

      - name: Run tests
        working-directory: backend
        run: |
          yarn install
          yarn test
